sudo: required
language: generic
services:
    - docker
        
before_install:
    - docker build -t vinothr90/docker-react -f Dockerfile.dev .
   
script:
    - docker run -e CI=true vinothr90/docker-react npm run test